name: 30 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Force Maven dependency update'
        run: mvn clean install -U

      - name: 'Remove corrupted logback dependency'
        run: rm -rf ~/.m2/repository/ch/qos/logback/logback-classic

      - name: 'Run License Finder'
        uses: jmservera/license-finder-action@main
        with:
          permitted-licenses: MIT,Apache-2.0,BSD,EPL-1.0
          approved-dependencies: |
            hamcrest,hamcrest-core,hamcrest-library
            junit-jupiter,junit-jupiter-api,junit-jupiter-engine,javax.annotation-api

      - name: 'Check if license_finder_report.xml exists'
        run: |
          if [ -f "${{ github.workspace }}/license_finder_report.xml" ]; then
            echo "Report exists."
          else
            echo "Report does not exist." && exit 1
          fi

      - name: 'Publish Test Results'
        if: success()
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        with:
          junit_files: "license_finder_report.xml"
          check_name: "License Compliance Check"

      - name: 'Upload Dependency Review Report'
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml
