name: 30 License Compliance with FOSSA

on:
  workflow_dispatch:
  workflow_call:

jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Force Maven dependency update'
        run: mvn clean install -U

      - name: 'Run FOSSA Scan'
        uses: fossas/fossa-action@main # Bloquea la versión para estabilidad
        with:
          api-key: ${{ secrets.FOSSA }}

      - name: 'Run FOSSA Test'
        uses: fossas/fossa-action@main
        with:
          api-key: ${{ secrets.FOSSA }}
          run-tests: true

      - name: 'Check FOSSA Report Exists'
        run: |
          if [ -f "${{ github.workspace }}/fossa_report.xml" ]; then
            echo "Report exists."
          else
            echo "Report does not exist." && exit 1
          fi

      - name: 'Upload FOSSA Report'
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: fossa-report
          path: ${{ github.workspace }}/fossa_report.xml

