name: 30 License Compliance

on:
  workflow_dispatch:
  workflow_call:

jobs:
  license-finder:
    # Usando https://github.com/pivotal/LicenseFinder
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'License Finder fix with mvnw (optional)'
        run: rm -f mvnw  # Asegúrate de que esto sea necesario. Si no lo es, puedes eliminar este paso.

      - name: 'Run License Finder'
        uses: jmservera/license-finder-action@main
        with:
          permitted-licenses: MIT,Apache-2.0,BSD,EPL-1.0
          approved-dependencies: |
            hamcrest,hamcrest-core,hamcrest-library
            junit-jupiter,junit-jupiter-api,junit-jupiter-engine,javax.annotation-api

      - name: 'Publish Test Results'
        uses: EnricoMi/publish-unit-test-result-action@v2.2.0
        if: always()
        with:
          junit_files: "license_finder_report.xml"
          check_name: "License Compliance Check"

      - name: 'Upload Dependency Review Report'
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: license-finder-report
          path: ${{ github.workspace }}/license_finder_report.xml
